global using Modding;
global using System.Collections;
global using System.Collections.Generic;
global using System.Reflection;
global using UnityEngine;
global using UObject = UnityEngine.Object;
global using USceneManager = UnityEngine.SceneManagement.SceneManager;
global using Satchel;
global using GlobalEnums;
global using System;
global using MonoMod.Cil;
global using MonoMod.Utils;
global using ReflectionHelper = Modding.ReflectionHelper;